### ISSUE TITLE
provide all voxels or single voxel

### ISSUE THREAD

**Issue by xtianmcd** [sheryl-ai/MVGCN#2]
For the input file "dti.coo.pkl" does the algorithm expect all the voxels for each ROI for each subject (where number of rows would be n_subjects x n_ROIs x n_voxels in each ROI), or does it expect a single voxel for each ROI, e.g., the center voxel (where number of rows would be n_subjects x n_ROIs x 1).

**Comment by xtianmcd** [comment]
I now see the loaded pkl file; are the node voxels the center coordinate for each ROI (e.g., median(X), median(Y), median(Z))?

**Comment by sheryl-ai** [comment]
Exactly. We computed the center coordinates for each ROI, and pickled results into the file "dti.coo.pkl". Here we used (mean(X), mean(Y), mean(Z)) .

**Comment by xtianmcd** [comment]
Thank you!! Closing issue :)
